name: PSR-12, Tests, Coverage
on:
  pull_request:
  push:
    branches:
      - master
      - main
      - dev

jobs:
  #  coding-standard:
  #    name: PSR-12 coding standard
  #    runs-on: ubuntu-latest
  #    if: github.ref != 'refs/heads/dev'
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v3
  #
  #      - uses: shivammathur/setup-php@v2
  #        with:
  #          php-version: 8.2
  #
  #      - name: Install PHP code sniffer
  #        run: composer global require squizlabs/php_codesniffer
  #
  #      - name: Check against PSR12 standard
  #        run: |
  #          `composer global config bin-dir --absolute --quiet`/phpcs --standard=PSR12 --ignore="src/Facades/*" ./src


  tests:
    #needs: coding-standard
    name: "PHP: ${{ matrix.php }} | Laravel: ${{ matrix.laravel }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4, 8.0, 8.1, 8.2 ]
        laravel: [ 6, 7, 8, 9, 10 ]
        exclude:
          - php: 8.1
            laravel: 6
          - php: 8.2
            laravel: 6

          - php: 8.1
            laravel: 7
          - php: 8.2
            laravel: 7

          - php: 7.4
            laravel: 9

          - php: 7.4
            laravel: 10
          - php: 8.0
            laravel: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis,apcu
          ini-values: apc.enable_cli=1

      - name: Install dependencies
        run: |
          composer require illuminate/support:^${{ matrix.laravel }} --no-interaction --prefer-dist

      # Laravel < 10 uses PHPUnit ^9.x
      - name: Run tests
        run: |
          if [[ ${{ matrix.laravel }} -lt 10 ]]; then
            ./vendor/bin/phpunit --configuration phpunit9.xml --testdox
          else
            ./vendor/bin/phpunit --configuration phpunit.xml --testdox
          fi

#  coverage:
#    needs: tests
#    name: Coverage
#    if: github.ref != 'refs/heads/dev'
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Install PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          coverage: pcov
#          php-version: 8.2
#          extensions: redis,apcu
#          ini-values: apc.enable_cli=1
#
#      - name: Install dependencies
#        run: composer install --no-interaction --prefer-dist
#
#      - name: Run tests for coverage
#        run: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.xml
#
#      - name: Push to Codecov
#        run: bash <(curl -s https://codecov.io/bash)
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
